name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main

jobs:
  test_build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Format code
        run: npm run format

      - name: Lint code
        run: npm run lint

      - name: Test code
        run: npm run test

      - name: Build app
        run: npm run build

      - name: Deploy app to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROFILE_PILOT }}'
          channelId: live
          projectId: profile-pilot

